STARTING_TRANSFERENCE = "iniciando transferencia\n".encode()
ABLE_TO_RECEIVE = "apto a receber\n".encode()
FILE_QUANTITY_RECEIVED = "quantidade de arquivos recebida\n".encode()
END_OF_FILE = "TX__EOF__RX\n".encode()
FILE_NAME_RECEIVED = "nome do arquivo recebido\n".encode()
FILE_LINE_RECEIVED = "linha recebida\n".encode()
UNABLE_TO_TRANSFER = "inapto a realizar transferencia\n".encode()
RESULTS_RECEIVED = "resultados recebidos com sucesso!\n".encode()
TRANSFERENCES_END = "transferencias finalizadas\n".encode()
FILE_TRANSFERENCE_SUCCES = "arquivo '{}' recebido e copiado com sucesso"
FILE_TRANSFERENCE_ERROR = "erro ao transferir arquivo '{}'. {}"